# Generated by Django 4.1.2 on 2022-11-07 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_name', models.CharField(max_length=60)),
                ('campus_email', models.EmailField(max_length=30)),
                ('campus_phone', models.CharField(max_length=60)),
                ('campus_address', models.CharField(max_length=100)),
                ('campus_manager', models.CharField(max_length=60)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.state')),
            ],
        ),
    ]
