# Generated by Django 4.1.2 on 2022-11-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_campus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_code', models.CharField(max_length=10)),
                ('qualification_name', models.CharField(max_length=60)),
                ('usage_recommendation', models.CharField(choices=[('CURRENT', 'CURRENT'), ('SUSPENDED', 'SUSPENDED')], max_length=50)),
                ('total_duration', models.IntegerField()),
                ('total_core_units', models.IntegerField()),
                ('total_elective_units', models.IntegerField()),
                ('total_units', models.IntegerField()),
                ('term', models.CharField(choices=[('Semester 3 Term 2', 'Semester 3 Term 2'), ('Semester 2 Term 2', 'Semester 2 Term 2'), ('Semester 4 Term 2', 'Semester 4 Term 2'), ('Semester 2 Term 1', 'Semester 2 Term 1'), ('Semester 4 Term 1', 'Semester 4 Term 1'), ('Semester 3 Term 1', 'Semester 3 Term 1'), ('Semester 1 Term 2', 'Semester 1 Term 2'), ('Semester 1 Term 1', 'Semester 1 Term 1')], max_length=100)),
                ('start_date', models.DateField()),
                ('proposed', models.DateField()),
                ('intake_date', models.DateField()),
            ],
        ),
    ]
