# Generated by Django 4.1.2 on 2022-11-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='term',
            field=models.CharField(choices=[('Semester 3 Term 1', 'Semester 3 Term 1'), ('Semester 2 Term 2', 'Semester 2 Term 2'), ('Semester 1 Term 2', 'Semester 1 Term 2'), ('Semester 1 Term 1', 'Semester 1 Term 1'), ('Semester 3 Term 2', 'Semester 3 Term 2'), ('Semester 4 Term 1', 'Semester 4 Term 1'), ('Semester 4 Term 2', 'Semester 4 Term 2'), ('Semester 2 Term 1', 'Semester 2 Term 1')], max_length=100),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='usage_recommendation',
            field=models.CharField(choices=[('SUSPENDED', 'SUSPENDED'), ('CURRENT', 'CURRENT')], max_length=50),
        ),
    ]
