# Generated by Django 4.1.2 on 2022-11-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_alter_qualification_term_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Break',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weeks', models.IntegerField()),
                ('title', models.CharField(max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='qualification',
            name='term',
            field=models.CharField(choices=[('Semester 4 Term 2', 'Semester 4 Term 2'), ('Semester 3 Term 2', 'Semester 3 Term 2'), ('Semester 1 Term 2', 'Semester 1 Term 2'), ('Semester 1 Term 1', 'Semester 1 Term 1'), ('Semester 2 Term 1', 'Semester 2 Term 1'), ('Semester 3 Term 1', 'Semester 3 Term 1'), ('Semester 2 Term 2', 'Semester 2 Term 2'), ('Semester 4 Term 1', 'Semester 4 Term 1')], max_length=100),
        ),
    ]
