# Generated by Django 4.1.2 on 2022-11-07 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_break_alter_qualification_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='term',
            field=models.CharField(choices=[('Semester 2 Term 2', 'Semester 2 Term 2'), ('Semester 3 Term 1', 'Semester 3 Term 1'), ('Semester 3 Term 2', 'Semester 3 Term 2'), ('Semester 1 Term 1', 'Semester 1 Term 1'), ('Semester 1 Term 2', 'Semester 1 Term 2'), ('Semester 4 Term 2', 'Semester 4 Term 2'), ('Semester 4 Term 1', 'Semester 4 Term 1'), ('Semester 2 Term 1', 'Semester 2 Term 1')], max_length=100),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='usage_recommendation',
            field=models.CharField(choices=[('CURRENT', 'CURRENT'), ('SUSPENDED', 'SUSPENDED')], max_length=50),
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_code', models.CharField(max_length=10)),
                ('unit_name', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('ELECTIVE', 'ELECTIVE'), ('CORE', 'CORE')], max_length=50)),
                ('duration', models.IntegerField()),
                ('class_hour', models.IntegerField()),
                ('unit_start_date', models.DateField()),
                ('unit_end_date', models.DateField()),
                ('assesment_due_date', models.DateField()),
                ('national_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Qualification.national_code +', to='timetable.qualification')),
                ('qualification_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Qualification.qualification_name +', to='timetable.qualification')),
            ],
        ),
    ]
