# Generated by Django 4.1.2 on 2022-11-07 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_alter_qualification_term_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='term',
            field=models.CharField(choices=[('Semester 2 Term 2', 'Semester 2 Term 2'), ('Semester 4 Term 1', 'Semester 4 Term 1'), ('Semester 3 Term 1', 'Semester 3 Term 1'), ('Semester 2 Term 1', 'Semester 2 Term 1'), ('Semester 3 Term 2', 'Semester 3 Term 2'), ('Semester 1 Term 1', 'Semester 1 Term 1'), ('Semester 1 Term 2', 'Semester 1 Term 2'), ('Semester 4 Term 2', 'Semester 4 Term 2')], max_length=100),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='usage_recommendation',
            field=models.CharField(choices=[('SUSPENDED', 'SUSPENDED'), ('CURRENT', 'CURRENT')], max_length=50),
        ),
        migrations.AlterField(
            model_name='units',
            name='national_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Qualification.national_code +', to='timetable.qualification'),
        ),
        migrations.AlterField(
            model_name='units',
            name='qualification_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Qualification.qualification_name +', to='timetable.qualification'),
        ),
    ]
