# Generated by Django 4.1.2 on 2022-11-21 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_remove_units_qualification_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='term',
            field=models.CharField(choices=[('Semester 2 Term 1', 'Semester 2 Term 1'), ('Semester 3 Term 2', 'Semester 3 Term 2'), ('Semester 4 Term 1', 'Semester 4 Term 1'), ('Semester 1 Term 1', 'Semester 1 Term 1'), ('Semester 2 Term 2', 'Semester 2 Term 2'), ('Semester 1 Term 2', 'Semester 1 Term 2'), ('Semester 3 Term 1', 'Semester 3 Term 1'), ('Semester 4 Term 2', 'Semester 4 Term 2')], max_length=100),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='usage_recommendation',
            field=models.CharField(choices=[('CURRENT', 'CURRENT'), ('SUPERSESEDED', 'SUPERSESEDED')], max_length=50),
        ),
        migrations.AlterField(
            model_name='units',
            name='status',
            field=models.CharField(choices=[('CORE', 'CORE'), ('ELECTIVE', 'ELECTIVE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='units',
            name='unit_code',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='units',
            name='unit_name',
            field=models.CharField(max_length=100),
        ),
    ]
