# Generated by Django 4.1.2 on 2022-11-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0009_alter_qualification_term_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='units',
            name='assesment_due_date',
        ),
        migrations.RemoveField(
            model_name='units',
            name='unit_end_date',
        ),
        migrations.AlterField(
            model_name='qualification',
            name='term',
            field=models.CharField(choices=[('Semester 4 Term 1', 'Semester 4 Term 1'), ('Semester 1 Term 2', 'Semester 1 Term 2'), ('Semester 2 Term 1', 'Semester 2 Term 1'), ('Semester 3 Term 1', 'Semester 3 Term 1'), ('Semester 4 Term 2', 'Semester 4 Term 2'), ('Semester 1 Term 1', 'Semester 1 Term 1'), ('Semester 2 Term 2', 'Semester 2 Term 2'), ('Semester 3 Term 2', 'Semester 3 Term 2')], max_length=100),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='usage_recommendation',
            field=models.CharField(choices=[('SUPERSESEDED', 'SUPERSESEDED'), ('CURRENT', 'CURRENT')], max_length=50),
        ),
        migrations.AlterField(
            model_name='units',
            name='status',
            field=models.CharField(choices=[('ELECTIVE', 'ELECTIVE'), ('CORE', 'CORE')], max_length=50),
        ),
    ]
