# Generated by Django 3.1.5 on 2022-11-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0010_remove_units_assesment_due_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='units',
            old_name='national_code',
            new_name='qualification',
        ),
        migrations.AlterField(
            model_name='break',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='term',
            field=models.CharField(choices=[('Semester 2 Term 1', 'Semester 2 Term 1'), ('Semester 2 Term 2', 'Semester 2 Term 2'), ('Semester 4 Term 2', 'Semester 4 Term 2'), ('Semester 3 Term 2', 'Semester 3 Term 2'), ('Semester 4 Term 1', 'Semester 4 Term 1'), ('Semester 3 Term 1', 'Semester 3 Term 1'), ('Semester 1 Term 2', 'Semester 1 Term 2'), ('Semester 1 Term 1', 'Semester 1 Term 1')], max_length=100),
        ),
        migrations.AlterField(
            model_name='state',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='units',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='units',
            name='status',
            field=models.CharField(choices=[('CORE', 'CORE'), ('ELECTIVE', 'ELECTIVE')], max_length=50),
        ),
    ]
