# Generated by Django 4.1.2 on 2022-12-05 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0011_auto_20221129_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='units',
            name='class_hour',
        ),
        migrations.RemoveField(
            model_name='units',
            name='unit_start_date',
        ),
        migrations.AlterField(
            model_name='break',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='term',
            field=models.CharField(choices=[('Semester 1 Term 2', 'Semester 1 Term 2'), ('Semester 2 Term 1', 'Semester 2 Term 1'), ('Semester 4 Term 1', 'Semester 4 Term 1'), ('Semester 4 Term 2', 'Semester 4 Term 2'), ('Semester 3 Term 2', 'Semester 3 Term 2'), ('Semester 2 Term 2', 'Semester 2 Term 2'), ('Semester 1 Term 1', 'Semester 1 Term 1'), ('Semester 3 Term 1', 'Semester 3 Term 1')], max_length=100),
        ),
        migrations.AlterField(
            model_name='state',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='units',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='units',
            name='status',
            field=models.CharField(choices=[('ELECTIVE', 'ELECTIVE'), ('CORE', 'CORE')], max_length=50),
        ),
    ]
